<?php
declare(strict_types=1);

namespace Pizzeria\Api;

use Kreait\Firebase\Exception\DatabaseException;
use Pizzeria\Connection\DbConnection;
use Pizzeria\Logger\ClientDataException;
use Pizzeria\Repository\IngredientRepository;
use Pizzeria\Validator\Elements\IngredientValidator;
use Pizzeria\Web\Request;

/**
 * Class Ingredient
 * @package Pizzeria\Api
 */
final class Ingredient extends GenericApi
{
    /**
     * @OA\Schema(
     *  schema="Ingredient",
     *  title="Ingredient",
     *  required={"name", "price"},
     *  @OA\Property(
     *      property="id",
     *      type="string",
     *      format="uuid",
     *      description="The ingredient unique key"
     *  ),
     *  @OA\Property(
     *      property="name",
     *      type="string",
     *      description="The ingredient name"
     *  ),
     *  @OA\Property(
     *      property="price",
     *      type="integer",
     *      description="The ingredient price"
     *  ),
     *  example={
     *     "id":"7f091d7a-e891-4d8b-934a-41c9b0be7825",
     *     "name":"ser",
     *     "price":2
     *    }
     * )
     */
    public const SCHEMA = ['id', 'name', 'price'];

    /**
     * Ingredient constructor.
     */
    public function __construct()
    {
        parent::__construct(new IngredientRepository(new DbConnection()), new IngredientValidator());
    }

    /**
     * @param Request $request
     * @return array
     * @throws DatabaseException
     * @throws ClientDataException
     *
     * @OA\Get(path="/PizzeriaServer/Api/Ingredient", tags={"Ingredient"},
     *      @OA\Response(response="200", description="Success",
     *          @OA\JsonContent(
     *              type="array",
     *              @OA\Items(ref="#/components/schemas/Ingredient")
     *          )
     *      )
     * )
     *
     *  @OA\Get(path="/PizzeriaServer/Api/Ingredient?name={ingredientName}", tags={"Ingredient"},
     *      @OA\Parameter(
     *          name="ingredientName",
     *          in="path",
     *          @OA\Schema(type="string")
     *      ),
     *      @OA\Response(response="200", description="Success",
     *          @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(ref="#/components/schemas/Ingredient")
     *          )
     *      ),
     *      @OA\Response(response="400", description="Bad Request",
     *          @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(ref="#/components/schemas/Error"),
     *              @OA\Examples(example="InvalidName", value={"message": "nonexistent ingredient name: 'SAMPLE_INGREDIENT'"}, summary="Invalid name")
     *          )
     *      )
     *  )
     */
    public function get(Request $request): array
    {
        return parent::get($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @return array
     * @throws ClientDataException
     * @throws DatabaseException
     *
     * @OA\Post(path="/PizzeriaServer/Api/Ingredient", tags={"Ingredient"},
     *     @OA\RequestBody(
     *         required=true,
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(ref="#/components/schemas/Ingredient")
     *         )
     *     ),
     *     @OA\Response(response="200", description="Success",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(ref="#/components/schemas/Sauce")
     *         )
     *     ),
     *     @OA\Response(response="400", description="Not Found",
     *         @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(ref="#/components/schemas/Error"),
     *              @OA\Examples(example="MissingProperty", value={"message":"missing ingredient property: 'SAMPLE_INGREDIENT'"}, summary="Missing property")
     *         )
     *     )
     * )
     */
    public function post(Request $request): array
    {
        return parent::post($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @return array
     * @throws ClientDataException
     * @throws DatabaseException
     *
     * @OA\Put(path="/PizzeriaServer/Api/Ingredient", tags={"Ingredient"},
     *     @OA\RequestBody(
     *         required=true,
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(ref="#/components/schemas/Ingredient")
     *         )
     *     ),
     *     @OA\Response(response="200", description="Success",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(ref="#/components/schemas/Ingredient")
     *         )
     *     ),
     *     @OA\Response(response="400", description="Not Found",
     *         @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(ref="#/components/schemas/Error"),
     *              @OA\Examples(example="MissingProperty", value={"message":"missing ingredient property: 'SAMPLE_INGREDIENT'"}, summary="Missing property")
     *         )
     *     )
     * )
     */
    public function put(Request $request): array
    {
        return parent::put($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @return array
     * @throws ClientDataException
     * @throws DatabaseException
     *
     * @OA\Delete(path="/PizzeriaServer/Api/Ingredient", tags={"Ingredient"},
     *     @OA\RequestBody(
     *         required=true,
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 required={"id"},
     *                 @OA\Property(property="id", type="string", format="uuid", example="7f091d7a-e891-4d8b-934a-41c9b0be7825")
     *             )
     *         )
     *     ),
     *     @OA\Response(response="200", description="Success",
     *         @OA\MediaType(
     *             mediaType="application/json",
     *             @OA\Schema(
     *                 required={"id"},
     *                 @OA\Property(property="id", type="string", format="uuid", example="7f091d7a-e891-4d8b-934a-41c9b0be7825")
     *             )
     *         )
     *     ),
     *     @OA\Response(response="400", description="Not Found",
     *         @OA\MediaType(
     *              mediaType="application/json",
     *              @OA\Schema(ref="#/components/schemas/Error"),
     *              @OA\Examples(example="MissingId", value={"message":"missing ingredient id property"}, summary="Missing id"),
     *              @OA\Examples(example="InvalidId", value={"message":"nonexistent ingredient id: 'SAMPLE_INGREDIENT_ID'"}, summary="Invalid id"),
     *         )
     *     )
     * )
     */
    public function delete(Request $request): array
    {
        return parent::delete($request); // TODO: Change the autogenerated stub
    }
}
