<?php
declare(strict_types=1);

namespace Pizzeria\Validator;

use Pizzeria\Repository\GenericRepository;
use RuntimeException;

class ModelValidator extends GenericValidator
{

    /**
     * @var array $decoratedValidator - list of GenericValidator
     */
    protected $decoratedValidators;

    public function __construct(GenericRepository $repository)
    {
        parent::__construct($repository);
    }

    /**
     * @param array $newProduct
     * @param bool $isSchemaRequired
     * @return bool
     */
    public function validate(array $newProduct, bool $isSchemaRequired = true): bool
    {
        parent::validate($newProduct, $isSchemaRequired); // TODO: Change the autogenerated stub

        $this->areElementsExist($newProduct);

        return true;
    }

    /**
     * @param array $newProduct
     * @param bool $areElementsRequired
     * @throws RuntimeException
     * @return bool
     */
    public function areElementsExist(array $newProduct, bool $areElementsRequired = true): bool
    {
        foreach ($this->decoratedValidators as $decoratedValidator) {
            $decoratedValidator->areElementsExist($newProduct[$decoratedValidator::ELEMENTS_GROUP], $areElementsRequired);
        }

        return true;
    }

    /**
     * @param GenericValidator $decoratedValidator
     */
    protected function addDecoratedValidators(GenericValidator $decoratedValidator): void
    {
        $this->decoratedValidators[] = $decoratedValidator;
    }
}